name: Docker Build

on:
  push:
    tags: [ 'v*' ]

env:
  DOCKER_HUB_NAMESPACE: luxorJD
  DOCKER_HUB_REPO: pcloudcc

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [ debian ]
        include:
          - flavor: debian
            dockerfile: ./Dockerfile
            platforms: linux/amd64,linux/arm64,linux/arm/v7

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_HUB_REPO }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_NAMESPACE }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push to Docker
      uses: docker/build-push-action@v3
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platforms }}
        push: ${{ !env.ACT && startsWith(github.ref, 'refs/tags/v') }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
